baseURL = '/'
languageCode = 'en-us'
title = 'Sanchit Bansal'
theme = 'terminal'

[languages.en.params.logo]
logoText = "Home 💻"

[menu]
  [[menu.main]]
    name = "Career"
    url = "/career/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 4

[params]
CenterTheme = true

